import { useEffect, useState } from 'react';

type Page = 'home' | 'assignments' | 'summary';
type Item = { id:number; name:string; kicker:string; title:string; description:string; highlights:string[]; pages:number; image:string; className:string; color:string };

const items: Item[] = [
  {id:1,name:'Bài tập 01',kicker:'Tệp & thư mục',title:'Thao tác cơ bản với tệp tin và thư mục',description:'Thực hành trực tiếp trên File Explorer: tạo cấu trúc thư mục, tạo và đổi tên tệp văn bản, sao chép, di chuyển, xóa vĩnh viễn và khôi phục dữ liệu từ Recycle Bin.',highlights:['Tạo cấu trúc lưu trữ khoa học','Phân biệt Copy/Paste và Cut/Paste','Thao tác xóa và khôi phục an toàn'],pages:10,image:'/objects/máy ảnh.png',className:'item-camera',color:'#f6c0d3'},
  {id:2,name:'Bài tập 02',kicker:'Thông tin học thuật',title:'Tìm kiếm và đánh giá thông tin học thuật',description:'Tìm kiếm và đánh giá nguồn học thuật về việc sử dụng ChatGPT, Claude và Gemini như hệ thống phản hồi viết tự động cho học sinh, sinh viên Việt Nam.',highlights:['Tìm kiếm đa kênh với từ khóa chiến lược','Đánh giá tác giả, cơ quan, phương pháp và trích dẫn','Đối chiếu tài liệu mới từ năm 2023'],pages:8,image:'/objects/gương.png',className:'item-mirror',color:'#efdde3'},
  {id:3,name:'Bài tập 03',kicker:'Prompt hiệu quả',title:'Viết Prompt hiệu quả cho các tác vụ học tập',description:'Thử nghiệm trên Gemini ba cấp độ prompt cho tóm tắt Người con gái Nam Xương, giải thích lạm phát và tạo câu hỏi về từ đồng âm trong quảng cáo.',highlights:['So sánh prompt cơ bản, cải tiến và nâng cao','Áp dụng role prompting và cấu trúc đầu ra','Đánh giá chiều sâu, độ chính xác và tính ứng dụng'],pages:11,image:'/objects/mac.png',className:'item-laptop',color:'#ead5dc'},
  {id:4,name:'Bài tập 04',kicker:'Cộng tác số',title:'Sử dụng công cụ hợp tác trực tuyến cho dự án nhóm',description:'Sử dụng Google Docs, Google Drive, Google Meet và Zoom để nghiên cứu ảnh hưởng của truyền thông đối với bản sắc văn hóa địa phương trong bài viết học thuật.',highlights:['Review Tracker theo dõi nhiệm vụ và deadline','Cộng tác, bình luận và lưu trữ nguồn','Họp nhóm, chọn tài liệu và xây dựng outline'],pages:6,image:'/objects/cốc.png',className:'item-cup',color:'#f5b6c9'},
  {id:5,name:'Bài tập 05',kicker:'AI sáng tạo',title:'Sử dụng AI tạo sinh để hỗ trợ sáng tạo nội dung',description:'Kết hợp Gemini, DALL·E và Canva AI để xây dựng bài thuyết trình về bốn nghi lễ chính trong đám cưới truyền thống Việt Nam.',highlights:['Gemini xây dựng và cải tiến dàn ý','DALL·E tạo hình minh họa từng nghi lễ','Canva AI hỗ trợ bố cục, sau đó cá nhân biên tập'],pages:7,image:'/objects/son.png',className:'item-lipstick',color:'#ff9fbd'},
  {id:6,name:'Bài tập 06',kicker:'AI trách nhiệm',title:'Sử dụng AI có trách nhiệm trong học tập và nghiên cứu',description:'Nghiên cứu chính sách AI và liêm chính học thuật tại ULIS; thực hành dùng AI hỗ trợ bài luận về ảnh hưởng của mạng xã hội đến kỹ năng giao tiếp của sinh viên ngoại ngữ.',highlights:['AI chỉ hỗ trợ ý tưởng và diễn đạt','Kiểm chứng qua Google Scholar và nguồn học thuật','Công khai, trích dẫn và chịu trách nhiệm với đầu ra'],pages:6,image:'/objects/notebook.png',className:'item-notebook',color:'#ffd2df'},
];

export default function App(){
 const [page,setPage]=useState<Page>('home');
 const [selected,setSelected]=useState<Item|null>(null);
 useEffect(()=>{window.scrollTo({top:0,behavior:'smooth'})},[page,selected]);
 return <div className="site-shell">
  <Header page={page} setPage={(next)=>{setSelected(null);setPage(next)}}/>
  {selected ? <AssignmentReader item={selected} onBack={()=>setSelected(null)}/> : <>
    {page==='home'&&<Home onExplore={()=>setPage('assignments')}/>} 
    {page==='assignments'&&<Assignments onSelect={setSelected}/>} 
    {page==='summary'&&<Summary onHome={()=>setPage('home')}/>} 
  </>}
 </div>
}

function Header({page,setPage}:{page:Page;setPage:(p:Page)=>void}){return <header className="topbar"><div aria-hidden="true"/><nav>{([['home','Trang chủ'],['assignments','Bài tập'],['summary','Tổng kết']] as [Page,string][]).map(([id,label])=><button className={page===id?'active':''} onClick={()=>setPage(id)} key={id}>{label}</button>)}<a href="https://drive.google.com/drive/folders/1BO06cEzoYXu0twPQhcJvkN1hO9tGoEik?usp=sharing" target="_blank" rel="noreferrer">Google Drive ↗</a></nav><div className="issue">PORTFOLIO <b>01</b></div></header>}

function Home({onExplore}:{onExplore:()=>void}){return <main className="home-page"><section className="hero"><div className="hero-copy"><p className="eyebrow">DIGITAL PORTFOLIO · VNU1001_E252063</p><h1>Nguyễn<br/><i>Hà Vy.</i></h1><p className="profile-line">MSSV 25040223 · Sư phạm Tiếng Anh · ULIS</p><p className="lead">Mình là Nguyễn Hà Vy, sinh viên ngành Sư phạm Tiếng Anh tại Trường Đại học Ngoại ngữ – ĐHQGHN. Portfolio này lưu lại sáu sản phẩm của học phần Nhập môn Công nghệ số và Ứng dụng trí tuệ nhân tạo, đồng thời phản ánh quá trình mình rèn luyện năng lực số, tư duy nghiên cứu và sử dụng AI có trách nhiệm.</p><div className="hero-actions"><button className="primary-btn" onClick={onExplore}>Khám phá bài tập <span>↗</span></button><span className="hand-note">six stories<br/>inside the bag ↓</span></div></div><div className="hero-art"><div className="cover-word">PORTFOLIO</div><div className="pink-orbit orbit-one"/><div className="pink-orbit orbit-two"/><div className="portrait-frame"><img src="/avatar.jpg" alt="Ảnh chân dung Nguyễn Hà Vy"/><span>NGUYỄN HÀ VY · ULIS</span></div><div className="cover-tag">THE<br/>NEW<br/><b>ACADEMIC</b><br/>CHIC</div><span className="edition-stamp">Nº 01</span></div></section><section className="ticker"><span>ENGLISH EDUCATION</span><b>✦</b><span>DIGITAL CRAFT</span><b>✦</b><span>CREATIVE INTELLIGENCE</span><b>✦</b><span>RESPONSIBLE AI</span></section></main>}

function Assignments({onSelect}:{onSelect:(x:Item)=>void}){return <main className="assign-page map-page"><section className="bag-stage bag-map" aria-label="Sáu bài tập tương tác"><p className="map-instruction">hover · shake · click ↗</p><p className="center-caption">My bag</p><img src="/objects/túi.png" alt="Chiếc túi trung tâm" className="center-bag"/>{items.map((item,index)=><button key={item.id} className={`object-button ${item.className}`} style={{'--delay':`${index*110}ms`} as React.CSSProperties} onClick={()=>onSelect(item)} aria-label={`Mở ${item.name}: ${item.kicker}`}><img src={item.image} alt=""/><span className="object-label"><b>0{item.id}</b>{item.kicker}</span></button>)}</section><div className="mobile-list">{items.map(item=><button key={item.id} onClick={()=>onSelect(item)}><img src={item.image} alt=""/><span><b>{item.name}</b><small>{item.kicker}</small></span><i>↗</i></button>)}</div></main>}

function AssignmentReader({item,onBack}:{item:Item;onBack:()=>void}){const file=`/files/Bai-${item.id}-Nguyen-Ha-Vy.pdf`;return <main className="reader-page"><button className="reader-back" onClick={onBack}>← Trở về bản đồ bài tập</button><header className="reader-header"><div><p className="eyebrow">ASSIGNMENT 0{item.id} · {item.pages} TRANG</p><h1>{item.title}</h1><p>{item.description}</p></div><div className="reader-object" style={{background:item.color}}><img src={item.image} alt="Vật dụng đại diện bài tập"/></div></header><section className="reader-document"><div className="reader-toolbar"><div><span className="reader-dot"/><b>BÁO CÁO ĐẦY ĐỦ</b><small>Chữ, hình ảnh và liên kết được giữ nguyên từ tài liệu gốc</small></div><a href={file} download>Tải PDF ↓</a></div><iframe src={`${file}#view=FitH&toolbar=1&navpanes=0`} title={`Báo cáo đầy đủ ${item.name}`}/><p className="pdf-fallback">Nếu trình duyệt không hiển thị tài liệu, <a href={file}>mở PDF tại đây</a>.</p></section><section className="lesson-section"><div className="lesson-title"><p className="eyebrow">AFTER THE EDIT</p><h2>Đúc kết<br/><i>bài học.</i></h2></div><div className="lesson-content"><p>{getLesson(item.id)}</p><ul>{item.highlights.map(x=><li key={x}><span>0{item.highlights.indexOf(x)+1}</span>{x}</li>)}</ul></div></section><div className="reader-end"><button className="primary-btn" onClick={onBack}>Xem bài tập khác</button><a className="ghost-btn link-btn" href={file} download>Lưu báo cáo PDF ↓</a></div></main>}

function getLesson(id:number){const lessons:Record<number,string>={1:'Qua bài thực hành, mình nhận ra một cấu trúc lưu trữ rõ ràng giúp tiết kiệm thời gian, hạn chế thất lạc dữ liệu và tạo nền tảng cho mọi công việc số về sau.',2:'Tìm được thông tin chưa đủ; người học cần biết thu hẹp phạm vi, đánh giá tác giả, phương pháp, độ cập nhật và đối chiếu nhiều nguồn trước khi sử dụng trong học thuật.',3:'Chất lượng đầu ra AI phụ thuộc trực tiếp vào vai trò, bối cảnh, yêu cầu và định dạng được nêu trong prompt. Thử nghiệm có hệ thống giúp biến AI thành trợ lý học tập hiệu quả hơn.',4:'Cộng tác trực tuyến hiệu quả cần nhiệm vụ rõ ràng, deadline cụ thể, lịch sử đóng góp minh bạch và một quy trình trao đổi thống nhất giữa các thành viên.',5:'AI có thể tăng tốc quá trình lên ý tưởng, tạo hình và thiết kế, nhưng cá nhân vẫn phải chọn lọc, chỉnh sửa và chịu trách nhiệm về tính phù hợp của sản phẩm cuối.',6:'Sử dụng AI có trách nhiệm nghĩa là công khai phạm vi hỗ trợ, kiểm chứng thông tin, diễn đạt bằng tư duy cá nhân và tuân thủ đầy đủ nguyên tắc liêm chính học thuật.'};return lessons[id]}

function Summary({onHome}:{onHome:()=>void}){return <main className="summary-v2"><header className="final-cover"><div className="final-copy"><p className="eyebrow">THE FINAL EDIT · NGUYỄN HÀ VY</p><h1>Khép lại một<br/><i>hành trình số.</i></h1><p>Sáu bài tập, sáu lát cắt của quá trình mình học cách tổ chức, nghiên cứu, cộng tác, sáng tạo và ứng xử có trách nhiệm trong môi trường số.</p><div className="final-meta"><span>VNU1001_E252063</span><span>2025—2026</span><span>ULIS · VNU</span></div></div><div className="final-portrait"><div className="portrait-number">06</div><img src="/avatar.jpg" alt="Nguyễn Hà Vy"/><p>Nguyễn Hà Vy<br/><small>Sư phạm Tiếng Anh</small></p></div></header>
  <section className="chapter lessons-chapter"><div className="chapter-index"><span>CHAPTER</span><b>01</b></div><div className="chapter-intro"><p className="eyebrow">WHAT I TAKE WITH ME</p><h2>Bài học<br/><i>rút ra.</i></h2></div><div className="lesson-editorial"><p className="lesson-lead">Công nghệ không thay thế tư duy; công nghệ mở rộng khả năng của mình khi được sử dụng đúng mục đích.</p><div className="lesson-list"><article><b>01</b><h3>Học có hệ thống</h3><p>Tổ chức tệp rõ ràng, quản lý tiến độ và lưu trữ minh chứng giúp quá trình học tập liền mạch hơn.</p></article><article><b>02</b><h3>Kiểm chứng trước khi tin</h3><p>Mọi nguồn tin và đầu ra AI đều cần được đối chiếu về tác giả, phương pháp, độ cập nhật và bối cảnh.</p></article><article><b>03</b><h3>Con người giữ vai trò quyết định</h3><p>AI hỗ trợ ý tưởng và tốc độ; lựa chọn, biên tập, lập luận cùng trách nhiệm cuối cùng vẫn thuộc về người học.</p></article><article><b>04</b><h3>Minh bạch tạo nên giá trị</h3><p>Trích dẫn đầy đủ và công khai phạm vi AI hỗ trợ là nền tảng của liêm chính học thuật.</p></article></div></div></section>
  <section className="chapter recap-chapter"><div className="recap-heading"><p className="eyebrow">A SIX-PIECE COLLECTION</p><span className="recap-no">02</span><h2>Tổng kết<br/><i>hành trình.</i></h2></div><div className="recap-body"><p>Từ thao tác tệp tin cơ bản đến nghiên cứu Generative AI trong phát triển kỹ năng viết tiếng Anh, mỗi bài tập bổ sung một lớp năng lực mới. Mình đã biết viết prompt rõ hơn, phối hợp nhóm có quy trình, kết hợp nhiều công cụ AI để tạo nội dung và nhận diện ranh giới giữa hỗ trợ hợp lý với phụ thuộc công nghệ.</p><div className="recap-tags"><span>Quản lý dữ liệu</span><span>Nghiên cứu học thuật</span><span>Prompt Engineering</span><span>Cộng tác số</span><span>Sáng tạo nội dung</span><span>AI có trách nhiệm</span></div><blockquote>“Sản phẩm cuối cùng quan trọng, nhưng cách mình tìm hiểu, kiểm chứng và hoàn thiện nó mới là phần đáng giá nhất.”</blockquote></div></section>
  <section className="thanks-chapter"><div className="thanks-decor">Thank<br/>you.</div><div className="thanks-copy"><p className="eyebrow">WITH GRATITUDE · 03</p><h2>Cảm ơn<br/><i>thầy cô.</i></h2><p>Em xin chân thành cảm ơn thầy cô đã xây dựng một học phần thiết thực, hướng dẫn tận tình và tạo cơ hội để em được thử nghiệm những công cụ mới trong học tập. Những nhận xét, yêu cầu và tiêu chuẩn của học phần đã giúp em hiểu rằng sử dụng công nghệ hiệu quả luôn phải đi cùng tư duy phản biện, tính chủ động và trách nhiệm học thuật.</p><p>Em sẽ tiếp tục vận dụng những kiến thức và kỹ năng đã học vào các học phần tiếp theo cũng như hành trình trở thành giáo viên tiếng Anh trong tương lai.</p><div className="signature">Nguyễn Hà Vy <span>— with gratitude</span></div></div><div className="thanks-stamp"><img src="/objects/gương.png" alt="Gương trang trí"/><span>KEEP<br/>LEARNING</span></div></section>
  <div className="summary-actions"><button className="primary-btn" onClick={onHome}>Trở về trang chủ</button><button className="ghost-btn" onClick={()=>window.scrollTo({top:0,behavior:'smooth'})}>Lên đầu trang ↑</button></div>
 </main>}
